# Generated by Django 5.1.1 on 2024-09-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='realease_date',
            new_name='release_date',
        ),
    ]
